import Head from 'next/head';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import webImages from '../public/webImages'; // Assuming you have a single file exporting all web images

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const toggleDarkMode = () => setDarkMode(prev => !prev);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>HELLO WORLD!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-900 transition-colors duration-500 px-6 md:px-12 lg:px-24">
        <section className="min-h-screen">
          <nav className="py-8 mb-12 flex justify-between items-center dark:text-white border-b border-gray-200 dark:border-gray-700">
            <h1 className="text-2xl font-semibold">HELLO WORLD!</h1>
            <ul className="flex items-center gap-6">
              <li>
                <BsFillMoonStarsFill
                  onClick={toggleDarkMode}
                  className="cursor-pointer text-2xl transition-transform duration-300 hover:scale-110"
                  aria-label="Toggle dark mode"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md shadow-lg hover:shadow-xl transition-shadow duration-300"
                  href="resume.pdf"
                  download="UmangP_Resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-8">
            <h2 className="text-4xl py-2 text-teal-600 font-semibold dark:text-teal-400 md:text-5xl">
              Umang Patel
            </h2>
            <h3 className="text-xl py-2 text-gray-800 dark:text-gray-200 md:text-2xl">
              Developer + UI/UX Designer
            </h3>
            <p className="text-lg py-5 leading-7 text-gray-800 dark:text-gray-200 max-w-3xl mx-auto md:text-xl">
              In search of my next adventure in the software engineering field, I am a skilled developer with almost 3 years of experience in React, Next.js, and Python. I excel at designing and developing applications, and am passionate about AI, Cloud computing, and Web Development. Eager to tackle new challenges and contribute to innovative projects.
            </p>
            <div className="text-4xl flex justify-center gap-6 py-4 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/umangp023/" aria-label="LinkedIn profile">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/umangp023" aria-label="GitHub profile">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-64 h-64 relative overflow-hidden mt-12 md:h-80 md:w-80">
              <Image src={deved} fill alt="Developer" style={{ objectFit: 'cover' }} />
            </div>
          </div>
        </section>
        <section>
          <div className="text-center py-8">
            <h3 className="text-3xl py-2 text-gray-800 dark:text-white">Portfolio</h3>
            <p className="text-lg py-4 leading-7 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto">
              I am a Software Engineer with experience in developing automation solutions, optimizing system alerts, and monitoring AWS environments. Currently at Evernorth, I specialize in Python and AWS for performance improvements. I’ve interned at Raytheon Technologies, where I enhanced project workflows using JIRA and agile methods, and at NSM Insurance Group, where I designed a C++ application for improving pipeline efficiency. I hold a Bachelor's in Computer Science from La Salle University and am proficient in multiple programming languages, including Java, JavaScript, and SQL.
            </p>
            <p className="text-lg py-4 leading-7 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto">
            In the future, I aim to integrate my back-end expertise with front-end development using React, JavaScript, and CSS to create user-centric applications. I seek to advance my skills in both cloud computing and automation, focusing on building scalable, efficient systems. My goal is to drive innovation and lead projects that enhance both system performance and user experience.
            </p>
          </div>
          <div className="lg:flex lg:gap-12 lg:flex-wrap">
            {[
              { src: design, title: 'Beautiful Designs', description: 'Creating elegant designs suited for your needs following core design theory.' },
              { src: code, title: 'Code your dream project', description: 'Do you have an idea for your next great website? Let\'s make it a reality.' },
              { src: consulting, title: 'Consulting', description: 'Are you interested in feedback for your current project? I can give you tips and tricks to level it up.' }
            ].map(({ src, title, description }, index) => (
              <div key={index} className="text-center shadow-lg p-8 rounded-xl my-8 dark:bg-gray-800 flex-1 transition-transform duration-300 hover:scale-105">
                <Image src={src} width={100} height={100} alt={title} />
                <h3 className="text-xl font-semibold pt-6 pb-2 text-gray-800 dark:text-gray-200">{title}</h3>
                <p className="py-2 text-gray-800 dark:text-gray-200">{description}</p>
                <h4 className="py-4 text-teal-600 dark:text-teal-400">Design Tools I Use</h4>
                <p className="text-gray-800 dark:text-gray-200 py-1">Photoshop</p>
                <p className="text-gray-800 dark:text-gray-200 py-1">Illustrator</p>
                <p className="text-gray-800 dark:text-gray-200 py-1">Figma</p>
                <p className="text-gray-800 dark:text-gray-200 py-1">Indesign</p>
              </div>
            ))}
          </div>
        </section>
        <section className="py-12">
          <div className="text-center">
            <h3 className="text-3xl py-2 text-gray-800 dark:text-white"></h3>
            <p className="text-lg py-4 leading-7 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto">
              <span className="text-teal-500 dark:text-teal-400"></span>  <span className="text-teal-500 dark:text-teal-400"></span>
            </p>
            <p className="text-lg py-4 leading-7 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto">
            </p>
          </div>
          <div className="flex flex-wrap gap-8 justify-center py-8">
            {webImages.map((image, index) => (
              <div key={index} className="basis-1/3 flex-1 rounded-lg overflow-hidden shadow-lg transition-transform duration-300 hover:scale-105">
                <Image
                  className="w-full h-full object-cover"
                  width={500}
                  height={300}
                  src={image}
                  alt={`Web project ${index + 1}`}
                />
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
